language: java
sudo: false
cache:
  directories:
    - $HOME/.m2
script:
  - set -e
  - mvn clean site -Psite --errors --batch-mode
  - mvn clean install -Pqulice --errors --batch-mode
install:
  - gem install pdd
  - gem install est
  - gem install xcop
env:
  global:
    - MAVEN_OPTS="-Xmx256m"
    - JAVA_OPTS="-Xmx256m"
jdk:
  - oraclejdk8
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
